### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by AnnaTheSucubuss** [MaxKlaxxMiner/blmchen_music_visualizer#1]
Why you published this to GitHub?
That code is not going to work at any way
If you don"t know how to do this just DO NOTHING

**Comment by MaxKlaxxMiner** [comment]
Hello Minzaker,

my plan for this project is:

- scan music files (frequencies, amplitude, times, stereo separations)
- manually/automatic helpers to find timestamps for beats, hi-hat, snare, crash etc.
- also helpers to determine pitches to find music notes, chors etc.
- manually adding detailed music-informations like lyric-texts etc.
- create sync profile-files for further processing (e.g. for real-time visualization)

Most of these things I've tested in past. "DO NOTHING" is not my plan... ;-)

next steps:

- decode aac-files to pcm-waveform (branch: aac-decoder)
- add player-functionality (with directsound, xaudio2 and asio)
- implement fast Fourier transform (FFT) for frequency analysis)
- create drawing-methods for amplitude- and spectrum-views
- gui with timeline-logic to mark beats etc.
